calkit/__init__.py, calkit/data.py, calkit/models.py, pyproject.toml
Also making data dependencies optional to make these easier to import elsewhere.
=> Start defining data models

calkit/cli.py
=> Add unified DVC/Git wrapper for 'calkit add'

calkit/cli/main.py
This is something I do all the time in multiple steps. Sort of nice to bundle it into one.
=> Add 'save' helper function to CLI to add, commit, and push all in one go

README.md, calkit/__init__.py, calkit/cli/core.py, calkit/cli/import_.py, calkit/cli/list.py, calkit/cli/main.py, calkit/cli/new.py, calkit/docker.py, calkit/dvc.py, calkit/models.py, calkit/tests/cli/test_list.py, calkit/tests/cli/test_main.py, calkit/tests/cli/test_new.py
Lots of new functionality here. Will be publishing a tutorial for usage soon.
=> Add ability to import datasets, manage/run environments, and enhance `new figure` command

calkit/__init__.py, calkit/cli/office.py, calkit/office.py
This is a non-backward-compatible change.
=> Make Excel chart extraction more general, allowing other image formats

calkit/__init__.py, calkit/cli/list.py, calkit/cli/main.py, calkit/cli/new.py, calkit/core.py, calkit/models.py, calkit/templates/__init__.py, calkit/templates/core.py, calkit/templates/latex/__init__.py, calkit/templates/latex/article/paper.tex, calkit/templates/latex/core.py, calkit/templates/latex/jfm/jfm.bst, calkit/templates/latex/jfm/jfm.cls, calkit/templates/latex/jfm/lineno-FLM.sty, calkit/templates/latex/jfm/paper.tex, calkit/templates/latex/jfm/upmath.sty, calkit/tests/cli/test_list.py, calkit/tests/cli/test_new.py, calkit/tests/test_templates.py, docs/tutorials/adding-latex-pub-docker.md
Will resolve #97 
```sh
calkit new publication ./paper \
--kind journal-article \
--template latex/jfm \
--environment latex \
--stage build-paper \
--title "Validating RANS models for a transitional boundary layer" \
--description "This is the main publication from this project."
```
Can use this Docker image: https://github.com/kjarosh/latex-docker
=> Add LaTeX publication generation from template, including Docker environment

README.md, calkit/__init__.py, calkit/cli/main.py, calkit/conda.py, docs/tutorials/conda-envs.md
=> Add function to check conda environment against a file

calkit/__init__.py, calkit/cli/main.py, calkit/cli/new.py, calkit/conda.py, docs/tutorials/conda-envs.md
- Ability to specify platform for Docker environments
- Ability to create a new Conda environment from the CLI
- Fixed a bug checking Conda environments that don't have pip dependencies in them
=> Add features and fixes inspired by the attempt to reproduce the UNH-RVAT Re dep results

calkit/__init__.py, calkit/cli/main.py, calkit/conda.py, calkit/core.py, calkit/magics.py
Lots of gotchas here trying to run on Windows.
=> Improve robustness of conda env checking and stage magic on Windows

calkit/__init__.py, calkit/cli/main.py, calkit/conda.py, calkit/tests/test_conda.py
This can be useful if you have an environment that's hard to get identical on different platforms.
=> Add `--relaxed` option to `check-conda-env`

calkit/cli/main.py
=> Check DVC remote auth by default in `calkit pull` and `calkit push`

calkit/__init__.py, calkit/cli/config.py, calkit/dvc.py
Thanks to @alexlib for discovering.
=> Improve error message output when trying to setup remote in non-project directory

calkit/__init__.py, calkit/check.py, calkit/cli/check.py, calkit/cli/main.py, calkit/dvc.py, calkit/tests/test_check.py
Some basic stuff to get a high level view and see where to head next.
=> Add `calkit check repro`, a basic reproducibility check with recommendations

calkit/__init__.py, calkit/check.py
=> Small fixes for repro check

calkit/cli/core.py, calkit/cli/new.py, calkit/core.py, calkit/dvc.py, calkit/git.py
=> Add ability to create a new project with the CLI

calkit/__init__.py, calkit/cli/main.py, calkit/cli/new.py, calkit/core.py, calkit/models.py, calkit/tests/cli/test_main.py, calkit/tests/cli/test_new.py
=> Add support for uv venvs on Windows and ability to create them from CLI

calkit/__init__.py, calkit/check.py, calkit/cli/import_.py, calkit/cli/main.py, calkit/cli/new.py, calkit/core.py
=> Add system-level dependency checking and fix some minor bugs

calkit/__init__.py, calkit/cli/main.py, calkit/core.py
=> Fix a bug checking for MATLAB dependency

calkit/__init__.py, calkit/cli/check.py, calkit/cli/main.py, calkit/cli/new.py, calkit/tests/cli/test_main.py, docs/tutorials/conda-envs.md
Also moved `check-conda-env` in there and updated the corresponding documentation.
Resolves #200
=> Rename `build-docker` command as `check docker-env`

calkit/__init__.py, calkit/cli/main.py, calkit/cli/new.py, calkit/tests/cli/test_new.py, docs/tutorials/existing-project.md, mkdocs.yml
=> Add tutorial for converting an existing project and `new stage` command to CLI

calkit/__init__.py, calkit/cli/main.py, docs/version-control.md
=> Add sync command

calkit/cli/import_.py, calkit/cli/new.py, calkit/core.py, calkit/dvc.py, calkit/git.py, calkit/server.py, calkit/tests/test_core.py, pyproject.toml, uv.lock
Want to do this with the Strava analysis project.
Towards #239
=> Work towards implementing `import environment`

.github/workflows/format.yml, .github/workflows/test.yml, calkit/__init__.py, calkit/cli/cloud.py, calkit/cli/main.py, calkit/tests/test_conda.py, calkit/tests/test_core.py, uv.lock
Helpful for testing tokens with `calkit cloud get user`.
Resolves #33.
=> Add cloud CLI and setup CI

.github/workflows/test.yml, calkit/__init__.py, calkit/cli/new.py, calkit/tests/cli/test_main.py, calkit/tests/test_check.py, calkit/tests/test_conda.py, uv.lock
Towards #274
Also fixed a few minor testing issues along the way. The tests are failing on my local Windows machine since they end up trying to run a Docker container and the shell is not a TTY. There's one additional test failing, and we also seem to hang at `test_magics.py`.
=> Add Windows tests to CI

calkit/__init__.py, calkit/cli/main.py, calkit/tests/cli/test_main.py
=> Always map current user ID when running Docker container

calkit/__init__.py, calkit/cli/new.py
For https://github.com/orgs/calkit/discussions/241#discussioncomment-13265169
=> Handle project with no environments in new stage

calkit/cli/main.py, calkit/cli/overleaf.py
Solves https://github.com/orgs/calkit/discussions/241#discussioncomment-13276823 
Note: I'm not sure how to make `calkit run` use my forked version instead of the version on uv, so I can't test if this works.
=> Ensure target uses a POSIX path in Overleaf import

calkit/__init__.py, calkit/dvc.py, calkit/pipeline.py, calkit/tests/test_dvc.py
Also close #353 since that's already the current behavior.
=> Fix bug reading DVC remotes with long names/URLs

calkit/__init__.py, calkit/cli/check.py
This doesn't seem to be useful information.
=> Remove Docker image descriptor from lockfile

calkit/__init__.py, calkit/cli/main.py, calkit/models/pipeline.py, calkit/pipeline.py, calkit/tests/cli/test_new.py, calkit/tests/models/test_pipeline.py, calkit/tests/test_pipeline.py
Thought about changing to `quiet`, since that's more conventional. On the other hand, maybe we should match the target system for pipeline arguments.
Resolves #261
=> Change LaTeX silent option to verbose and add synctex

calkit/conda.py
=> Only use mamba if installed, solving #410

calkit/cli/new.py
=> Configure DVC remote when creating new project from existing repo

calkit/__init__.py, calkit/cli/notebooks.py, calkit/tests/cli/test_notebooks.py, test/nb-subdir.ipynb
Resolves #468 
This is a difference between nbconvert and papermill.
=> Set working directory to notebook directory when executing

calkit/cli/main.py
=> Make run logging opt-in instead of opt-out

calkit/__init__.py, calkit/cli/config.py
=> Add command to configure GitHub SSH key
