calkit/__init__.py, calkit/cli/__init__.py, calkit/cli/config.py, calkit/cli/core.py, calkit/cli/main.py, calkit/cli/new.py, calkit/cli/notebooks.py
The use case for this is, e.g., in a DVC pipeline, where one step is manual, it probably produces an output, and we want to block until the user confirms it's done.
Example pipeline:
```yaml
stages:
do-manual-thing:
cmd: calkit manual-step -m "Save the output to figures/fig.png" --cmd "matlab"
outs:
- figures/fig.png
deps:
- scripts/my-interactive-script.m
- data/my-data.csv
run-data-collection:
cmd: calkit manual-step -m "Execute the runs" --cmd "turbinedaq ."
outs:
- data/raw
deps:
- plan/runs.csv
```
For that last stage, how can we ensure it runs if all of the raw data is not there yet, similar to how TurbineDAQ works? Maybe we always want it to run, but build the logic into `calkit` to examine a chunked step? We could also make it a matrix stage, but then we're executing the command …
=> Add ability to run a manual step from the CLI and automatically add objects in `calkit run`

README.md, calkit/__init__.py, calkit/cli/main.py
The name of the Calkit env does not need to match that of the Conda env, though it's probably a good idea to do so.
=> Read conda env name from environment file in runenv

calkit/__init__.py, calkit/cli/main.py
=> Add support for Pixi, uv environments and add checking to `calkit runenv`

.gitignore, calkit/__init__.py, calkit/calc.py, calkit/cli/main.py, calkit/tests/test_calc.py, pyproject.toml
Towards #34 
Ultimate usage will be on the web front end. Users can ship a calculation with their project, e.g., one that computes predictions from things discovered in their paper, and we can show that interactively on the homepage.
=> Add functionality to evaluate arithmetic expressions and linear calculations

README.md, calkit/check.py, calkit/cli/config.py, calkit/cli/new.py, calkit/git.py
Resolves #60 
Example:
```sh
calkit new project --cloud --title "Test 7" --template calkit/example-basic test-7 --public
```
Cloud integration depends on changes in https://github.com/calkit/calkit-cloud/pull/245.
=> Allow creating new projects from templates

calkit/__init__.py, calkit/conda.py, calkit/tests/test_conda.py
=> Allow more flexible version specifiers in conda.check_env

calkit/__init__.py, calkit/cli/main.py, calkit/cli/new.py, calkit/magics.py, calkit/models.py, calkit/tests/cli/test_main.py, calkit/tests/cli/test_new.py, docs/tutorials/conda-envs.md, docs/tutorials/procedures.md
Want to avoid confusion with `run` and use commands like `uvx`.
Resolves #159.
=> Alias `xenv` to `runenv` and `xproc` to `runproc`

calkit/__init__.py, calkit/cli/main.py, calkit/cli/new.py, calkit/models.py, calkit/tests/cli/test_main.py
Example:
```sh
calkit new venv --name my-venv "pandas>=2.0"
```
```sh
calkit xenv -n my-venv -- python -c "import pandas; print(pandas.__version__)"
```
=> Add compatibility with Python's built-in `venv` module

calkit/cli/new.py, calkit/models.py, calkit/tests/cli/test_main.py
Resolves #144 
```sh
calkit new pixi-env -n pixi1 pandas polars numpy
```
```sh
calkit xenv -n pixi1 -- which python
```
=> Add ability to create a new pixi env from the command line

calkit/cli/new.py
This was a bit of a bug, where if you had two pixi envs and used `--overwrite` to create a new one, the others would be deleted.
=> Don't delete pixi.toml file and use --force to create pixi env

calkit/cli/core.py, calkit/core.py
=> Add ability to declare environmental variables and config items as project dependencies

.gitignore, calkit/__init__.py, calkit/cli/check.py, calkit/cli/main.py, calkit/models.py, calkit/ops.py, calkit/server.py, calkit/tests/cli/test_main.py, calkit/tests/test_check.py, pyproject.toml
- Parse `.env` files before running pipeline or commands in environments -- resolves #122 
- Make `save --all` automatically add or ignore untracked files -- towards #156 
- Started ops model -- towards #90
=> Improve UX

.github/workflows/docs.yml, calkit/__init__.py, calkit/cli/main.py, calkit/core.py, calkit/dvc.py, calkit/git.py, calkit/models.py, calkit/tests/cli/test_main.py, docs/version-control.md, mkdocs.yml, pyproject.toml
=> Make version control UX easier

.gitignore, calkit/__init__.py, calkit/cli/check.py, calkit/cli/main.py, calkit/conda.py, calkit/tests/cli/test_main.py, docs/environments.md, pyproject.toml, uv.lock
Resolves #203 
Also fixed some issues with Docker shell commands and working directories so we get expected results. The command sent into `calkit xenv` should never have `&&` in it, since that indicates a new shell command after.
=> Add explicit dependency checking against MD5s for Docker envs

calkit/__init__.py, calkit/cli/main.py, calkit/models.py, docs/environments.md, docs/examples.md
Resolves #14 
Example project: https://github.com/calkit/example-ssh
=> Add remote SSH environment support

calkit/__init__.py, calkit/cli/main.py, calkit/tests/cli/test_main.py
We also prompt the user to create a Git repo if one does not exist.
=> Allow using `.` in `calkit add`

calkit/__init__.py, calkit/cli/config.py
If we don't do this, DVC will complain if we try to push, since it needs to read a committed config file.
=> Make calkit config remote commit changes by default

calkit/__init__.py, calkit/cli/main.py, docs/calkit-yaml.md, docs/datasets.md, docs/version-control.md, mkdocs.yml
- `calkit clone` can now reference a project owner/name instead of a full URL
- `calkit ignore` will add a file to `.gitignore` if necessary
Towards #156
=> Add datasets docs and more Git helper functionality

calkit/__init__.py, calkit/cli/config.py, calkit/cli/core.py, calkit/cli/main.py, calkit/cli/new.py, calkit/core.py, calkit/dvc.py, calkit/git.py, calkit/models.py, calkit/tests/cli/test_main.py
Related to https://github.com/calkit/calkit-cloud/issues/110
We can store project status completely locally in the repo and GET/POST via API.
=> Add project status log

calkit/__init__.py, calkit/cli/import_.py, calkit/cloud.py, calkit/config.py, calkit/dvc.py, calkit/models.py, pyproject.toml, uv.lock
Similar use case as https://github.com/calkit/calkit-cloud/issues/335
=> Make dataset importing more flexible

calkit/__init__.py, calkit/cli/check.py
If a project has environmental variable dependencies defined, this will iterate through them, and if they're not defined, prompt the user for them and add the supplied value to `.env`.
=> Add `check env-vars` command

calkit/__init__.py, calkit/cli/main.py
Use `posixpath` instead of `os.path.join` so we use POSIX paths in the container.
=> Fix bug specifying `--wdir` for `xenv` with Docker

calkit/__init__.py, calkit/cli/main.py, calkit/git.py, calkit/tests/cli/test_main.py
If one is continuously iterating on a single file, this can help speed things up
```sh
calkit save -aM
```
In the future it would be nice to have a VS Code extension that allows saving one file and creating an automated commit message for it (#216).
=> Add ability to create automatic commit message if saving one path

calkit/__init__.py, calkit/check.py, calkit/cli/main.py, calkit/cli/new.py, calkit/conda.py, calkit/tests/test_conda.py, docs/environments.md
=> Allow defining prefix for Conda envs

README.md, calkit/__init__.py, calkit/cli/core.py, calkit/cli/import_.py, calkit/cli/main.py, calkit/cli/new.py, calkit/dvc.py, calkit/magics.py, calkit/ops.py, calkit/server.py, calkit/templates/core.py, calkit/tests/cli/test_main.py, calkit/tests/cli/test_new.py, calkit/tests/test_check.py, calkit/tests/test_conda.py, calkit/tests/test_dvc.py, calkit/tests/test_magics.py, docs/installation.md, pyproject.toml
=> Add wrapper for DVC CLI and use `python -m dvc` internally

calkit/__init__.py, calkit/cli/config.py, calkit/config.py, calkit/tests/cli/test_config.py, pyproject.toml, uv.lock
Resolves #251 
Will read from plain text if present, but will write only to keyring on next update.
=> Use keyring for secrets if supported

calkit/__init__.py, calkit/cli/check.py
Causing a false positive environment diff when switching between computers with different uv versions.
=> Ensure color does not make it into venv lock files

calkit/__init__.py, calkit/cli/new.py
Sometimes it makes sense to put env definition files in a folder if you have many of them.
=> Create necessary subdirectories for env paths

calkit/__init__.py, calkit/cli/check.py, calkit/cli/main.py, calkit/conda.py, calkit/tests/cli/test_check.py
Related to #400 
Resolves #229 
Resolves #426, though it doesn't fully check the dependency versions when they have optional dependencies or Git versions.
=> Try to use lock files to recreate venvs

calkit/__init__.py, calkit/models/pipeline.py, calkit/tests/cli/test_new.py, calkit/tests/models/test_pipeline.py
Resolves #533 
Note that we will not pick up on one automatically. It needs to be specified explicitly so we can track it as a DVC dependency.
=> Allow specifying latexmkrc path for LaTeX stages
